# SPDX-FileCopyrightText: 2025 Tobias Böhm <code@aibor.de>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
version: "2"

linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - funlen
    - paralleltest
    - varnamelen
  settings:
    lll:
      line-length: 80
      tab-width: 4
  exclusions:
    generated: strict
    warn-unused: true

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    golines:
      max-len: 80
