# SPDX-FileCopyrightText: 2024 Tobias Böhm <code@aibor.de>
#
# SPDX-License-Identifier: GPL-3.0-or-later

linters:
  enable-all: true
  disable:
    - depguard
    - execinquery
    - exhaustruct
    - exportloopref
    - funlen
    - gomnd
    - paralleltest
    - varnamelen

  linters-settings:
    lll:
      line-length: 80

issues:
  exclude-use-default: false
