# SPDX-FileCopyrightText: 2024 Tobias Böhm <code@aibor.de>
#
# SPDX-License-Identifier: MIT

linters:
  enable-all: true
  disable:
    - depguard
    - execinquery
    - exhaustruct
    - exportloopref
    - funlen
    - gomnd
    - paralleltest
    - varnamelen

issues:
  exclude-use-default: false
