# SPDX-FileCopyrightText: 2025 Tobias Böhm <code@aibor.de>
#
# SPDX-License-Identifier: GPL-3.0-or-later

project_name: timewarrior-extensions

version: 2

gomod:
  proxy: true

builds:
  - id: flextime
    main: ./cmd/flextime
    binary: flextime
    mod_timestamp: "{{.CommitTimestamp}}"
    flags:
      - -trimpath
    goos:
      - linux
      - freebsd
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    formats: binary

release:
  header: |
    ## {{ .TagSubject }} ({{ .Now.Format "2006-01-02" }})
    {{ .TagBody }}

snapshot:
  version_template: "{{ .Tag }}"

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

changelog:
  sort: "asc"
  use: "github"
  filters:
    include:
      - "^feat"
      - "^fix"
